### PR TITLE
Fix wrong offset if tag is null

### PR DESCRIPTION
**Pull request by lujiajing1126**

### CODE REVIEW

**Comment by lujiajing1126** [comment]
Can you pls have a test with 0.3.0-SNAPSHOT @wankai123

**Comment by wankai123** [comment]
> Can you pls have a test with 0.3.0-SNAPSHOT @wankai123

OK

**Review by wankai123 — APPROVED** [review]
Have tested it in my local env.

**Comment by wu-sheng** [comment]
Once all tests are verified for Zipkin, we could create a `0.2.x` branch for a patch releasing to make OAP 9.3.0 release done.

**Pull request merged**
