### PR TITLE
Introduce the Float field type

### PR DESCRIPTION
**Pull request by hanahmily**
Introduce the Float field type and suppress the resource not found error on loading on-disk streams/measures.

Related to https://github.com/apache/skywalking/issues/8940

### CODE REVIEW

**Comment by wu-sheng** [comment]
Why should we suppress the resource not found error?

**Comment by hanahmily** [comment]
> Why should we suppress the resource not found error?

A stream or measure might not link to any index rules. Considering a measure without index rules, throwing such an error would mess up the initialization. In the OAP scenario, the installation procedure will be interrupted when loading existing measures from the disk. Then the OAP server will crash down.

**Comment by wu-sheng** [comment]
> > Why should we suppress the resource not found error?
> 
> 
> 
> A stream or measure might not link to any index rules. Considering a measure without index rules, throwing such an error would mess up the initialization. In the OAP scenario, the installation procedure will be interrupted when loading existing measures from the disk. Then the OAP server will crash down. 
> 
> 
> 
> 

Do you mean due to last time bug? I don't think we intend to have no rule.

**Comment by hanahmily** [comment]
> I don't think we intend to have no rule.

Service-level metrics don't need any index rules. All searchable tags belong to the entity(SeriesID). 

> Do you mean due to last time bug? 

 It's from an [improvement](https://github.com/apache/skywalking-banyandb-java-client/commit/f79cef58b07b6d9316eba75d7f5f2aa357c5691f) more than a bug. We don't create the indexRuleBinding when there is no indexRule. But the measure initialization procedure is based on the assumption that there is an indexRuleBinding at least. That is why an indexRuleBinding not found error is raised.

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
