### PR TITLE
Fix aggregation and value type

### PR DESCRIPTION
**Pull request by Superskyyy**
1. SumBy uses wrong aggregation method, was COUNT should be SUM
2. Missing the float tag type field when doing write.

### CODE REVIEW

**Comment by Superskyyy** [comment]
Found these during internal testing. Not sure if fix is correct, please take a look.

**Comment by lujiajing1126** [comment]
where do we need float？

**Comment by wu-sheng** [comment]
I think server side doesn't support float yet, too. Right?

**Comment by Superskyyy** [comment]
> where do we need float？

To record some fractional data like memory usage. Is this currently not supported?

**Comment by Superskyyy** [comment]
> I think server side doesn't support float yet, too. Right?
https://github.com/apache/skywalking-banyandb/pull/240 Looks like it's there?

**Review by lujiajing1126 — APPROVED** [review]
LGTM

**Pull request merged**
