### PR TITLE
Add several functionalities to the BanyanDBClient

### PR DESCRIPTION
**Pull request by hanahmily**
* DNS name resolution
* Multiple addresses
* Load balancing

### CODE REVIEW

**Comment by lujiajing1126** [comment]
I suppose DNS resolution is by default supported by gRPC client.

**Comment by wu-sheng** [comment]
I remember it would not refresh in time? Java agent is trying to resolve when reconnect or periodically.

**Comment by hanahmily** [comment]
The DNS resoluvor doesn't expose any configuration to control its
behaviors. Besides that, a customer resolver can not handle the mix of DNS
and IP addresses.

Based on that, I implemented a lower level solution to support all
behaviors we care of.

**Review by wu-sheng — APPROVED** [review]
FYI @wankai123 @lujiajing1126 This seems like a breaking change. We need to update OAP side implementation to adopt this new constructor.

**Pull request merged**
